spring.application.name=api
spring.profiles.active=development

spring.datasource.url=jdbc:postgresql://db:5432/shl
spring.datasource.username=pguser
spring.datasource.password=example

spring.jpa.hibernate.ddl-auto=update