// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for ShlController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, ShlTeam, GuessPlayerViewInput, ShlPlayer, GuessPlayerViewOutput, PlayerNameViewOutput } from "../models";

@Injectable({ providedIn: "root" })
export class ShlControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    syncTeams(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<ShlTeam>>;
    syncTeams(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<ShlTeam>>>;
    syncTeams(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<ShlTeam>>>;
    syncTeams(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/shl/teams/sync`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    syncPlayers(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    syncPlayers(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    syncPlayers(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    syncPlayers(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/shl/players/sync`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('post', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    guessPlayer(guessPlayerViewInput: GuessPlayerViewInput, observe?: 'body', options?: RequestOptions<'json'>): Observable<ShlPlayer>;
    guessPlayer(guessPlayerViewInput: GuessPlayerViewInput, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ShlPlayer>>;
    guessPlayer(guessPlayerViewInput: GuessPlayerViewInput, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ShlPlayer>>;
    guessPlayer(guessPlayerViewInput: GuessPlayerViewInput, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/shl/player/guess`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: guessPlayerViewInput,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    allTeams(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<ShlTeam>>;
    allTeams(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<ShlTeam>>>;
    allTeams(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<ShlTeam>>>;
    allTeams(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/shl/teams`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    fetchByTeam(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<ShlPlayer>>;
    fetchByTeam(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<ShlPlayer>>>;
    fetchByTeam(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<ShlPlayer>>>;
    fetchByTeam(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/shl/teams/${id}/players`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getPlayer(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ShlPlayer>;
    getPlayer(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ShlPlayer>>;
    getPlayer(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ShlPlayer>>;
    getPlayer(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/shl/player/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    randomPlayerFromTeam(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<GuessPlayerViewOutput>;
    randomPlayerFromTeam(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GuessPlayerViewOutput>>;
    randomPlayerFromTeam(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GuessPlayerViewOutput>>;
    randomPlayerFromTeam(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/shl/player/${id}/random`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    randomPlayer(observe?: 'body', options?: RequestOptions<'json'>): Observable<GuessPlayerViewOutput>;
    randomPlayer(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GuessPlayerViewOutput>>;
    randomPlayer(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GuessPlayerViewOutput>>;
    randomPlayer(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/shl/player/random`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    playerNames(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<PlayerNameViewOutput>>;
    playerNames(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<PlayerNameViewOutput>>>;
    playerNames(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<PlayerNameViewOutput>>>;
    playerNames(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/shl/player/playernames`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
