// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface ShlTeam {
    uuid?: string;
    teamCode?: string;
}

export interface GuessNumberViewInput {
    id?: string;
    jerseyNumber?: number;
}

export interface ShlPlayer {
    uuid?: string;
    firstName?: string;
    lastName?: string;
    fullName?: string;
    nationality?: string;
    jerseyNumber?: number;
    renderedLatestPortrait?: ShlRenderedMedia;
    team?: ShlTeam;
}

export interface ShlRenderedMedia {
    url?: string;
}

export interface GuessNameViewInput {
    id?: string;
    name?: string;
}

export enum GameType {
    GUESS_NAME = "GUESS_NAME",
    GUESS_NUMBER = "GUESS_NUMBER"
}

export interface GuessPlayerViewOutput {
    uuid?: string;
    imgUrl?: string;
    name?: string;
    jerserNumber?: number;
}

export interface PlayerNameViewOutput {
    name?: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
